import "./globals.css";
import config from "@/config/config";
import TopHeader from "@/components/TopHeader";
import MainHeader from "@/components/MainHeader";
import HeaderCategories from "@/components/HeaderCategories";

export const metadata = {
  title: config.appName,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TopHeader />
        <div className="w-full z-50 sticky top-0 bg-white">
          <MainHeader/>
        </div>
        <div>
          <HeaderCategories/>
        </div>
        {children}
      </body>
    </html>
  );
}
