import MainLayout from "@/layout/MainLayout";
import "./globals.css";
import config from "@/config/config";

export const metadata = {
  title: config.appName,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainLayout />
        {children}
      </body>
    </html>
  );
}
