import "./globals.css";
import config from "@/config/config";

import MainLayout from "@/layout/MainLayout";
import Provider from "@/redux/Provider.js";


export const metadata = {
  title: config.appName,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className="">
        <Provider>
          <MainLayout className=''>{children}</MainLayout>
        </Provider>
      </body>
    </html>
  );
}
